apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: primaza-controller-agentsvc
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: primaza
    app.kubernetes.io/part-of: primaza
    app.kubernetes.io/managed-by: kustomize
  name: primaza-controller-agentsvc
