version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    ignore:
      # These projects usually require more manual intervention to bump than
      # usual, so let's ignore them from normal dependabot updates for now.
      - dependency-name: "k8s.io/*"
      - dependency-name: "sigs.k8s.io/*"

  - package-ecosystem: pip
    directory: "test/acceptance/features/"
    schedule:
      interval: weekly

  - package-ecosystem: pip
    directory: "hack/check-python/"
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: "deploy/"
    schedule:
      interval: weekly
