package authz

var AppPermissionList = []Permission{
	{
		APIGroups:     []string{"primaza.io"},
		Resources:     []string{"servicebindings", "serviceclaims", "servicecatalogs"},
		ResourceNames: []string{},
		Namespace:     "system",
		Name:          "primaza:app:manager",
		Verbs:         []string{"get", "list", "watch", "update", "patch", "delete", "deletecollection"},
	},
	{
		APIGroups:     []string{"primaza.io"},
		Resources:     []string{"serviceclaims/status"},
		ResourceNames: []string{},
		Namespace:     "system",
		Name:          "primaza:app:manager",
		Verbs:         []string{"get", "list", "watch", "update"},
	},
	{
		APIGroups:     []string{"primaza.io"},
		Resources:     []string{"servicebindings/status"},
		ResourceNames: []string{},
		Namespace:     "system",
		Name:          "primaza:app:manager",
		Verbs:         []string{"get", "list", "watch", "update"},
	},
	{
		APIGroups:     []string{"apps"},
		Resources:     []string{"deployments"},
		ResourceNames: []string{},
		Namespace:     "system",
		Name:          "primaza:app:manager",
		Verbs:         []string{"get", "list", "watch", "update", "patch"},
	},
	{
		APIGroups:     []string{"apps"},
		Resources:     []string{"deployments", "deployments/finalizers"},
		ResourceNames: []string{"primaza-app-agent"},
		Namespace:     "system",
		Name:          "primaza:app:manager",
		Verbs:         []string{"update"},
	},
	{
		APIGroups:     []string{""},
		Resources:     []string{"secrets"},
		ResourceNames: []string{},
		Namespace:     "system",
		Name:          "primaza:app:manager",
		Verbs:         []string{"list", "get", "watch", "update"},
	},
	{
		APIGroups:     []string{"primaza.io"},
		Resources:     []string{"servicebindings/finalizers"},
		ResourceNames: []string{},
		Namespace:     "system",
		Name:          "primaza:app:manager",
		Verbs:         []string{"update"},
	},
	{
		APIGroups:     []string{"coordination.k8s.io"},
		Resources:     []string{"leases"},
		ResourceNames: []string{},
		Namespace:     "system",
		Name:          "primaza:app:leader-election",
		Verbs:         []string{"get", "list", "watch", "create", "update", "patch", "delete"},
	},
	{
		APIGroups:     []string{""},
		Resources:     []string{"events"},
		ResourceNames: []string{},
		Namespace:     "system",
		Name:          "primaza:app:leader-election",
		Verbs:         []string{"create", "patch"},
	},
}
