# permissions for end users to edit clusterenvironments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: clusterenvironment-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: primaza
    app.kubernetes.io/part-of: primaza
    app.kubernetes.io/managed-by: kustomize
  name: clusterenvironment-editor-role
rules:
- apiGroups:
  - primaza.io.primaza.io
  resources:
  - clusterenvironments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - primaza.io.primaza.io
  resources:
  - clusterenvironments/status
  verbs:
  - get
