# permissions for end users to view serviceclasses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: serviceclass-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: primaza
    app.kubernetes.io/part-of: primaza
    app.kubernetes.io/managed-by: kustomize
  name: serviceclass-viewer-role
rules:
- apiGroups:
  - primaza.io.primaza.io
  resources:
  - serviceclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - primaza.io.primaza.io
  resources:
  - serviceclasses/status
  verbs:
  - get
