apiVersion: apps/v1
kind: Deployment
metadata:
  name: primaza-app-agent
  labels:
    app.kubernetes.io/part-of: primaza
    control-plane: primaza-app-agent
  finalizers:
  - agentapp.primaza.io/finalizer
spec:
  selector:
    matchLabels:
      control-plane: primaza-app-agent
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: primaza-app-agent
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /manager
        args:
        - --leader-elect
        image: agentapp:latest
        imagePullPolicy: IfNotPresent
        name: manager
        env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: primaza-app-agent
      terminationGracePeriodSeconds: 10
