apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../bases/primaza.io_serviceclasses.yaml
- ../../bases/primaza.io_registeredservices.yaml
configurations:
- ../../kustomizeconfig.yaml
patches:
- path: ../../patches/cainjection_in_serviceclasses.yaml
  target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    version: v1
- path: ../../patches/webhook_in_serviceclasses.yaml
  target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    version: v1
