apiVersion: primaza.io.primaza.io/v1alpha1
kind: ClusterEnvironment
metadata:
  labels:
    app.kubernetes.io/name: clusterenvironment
    app.kubernetes.io/instance: clusterenvironment-sample
    app.kubernetes.io/part-of: primaza
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: primaza
  name: clusterenvironment-sample
spec:
  # TODO(user): Add fields here
