apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: primaza:app:manager
  namespace: system
rules:
- apiGroups:
  - primaza.io
  resources:
  - servicebindings
  - serviceclaims
  - servicecatalogs
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - delete
  - deletecollection
- apiGroups:
  - primaza.io
  resources:
  - serviceclaims/status
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - primaza.io
  resources:
  - servicebindings/status
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  - deployments/finalizers
  verbs:
  - update
  resourceNames:
  - primaza-app-agent
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - get
  - delete
  - watch
  - update
- apiGroups:
  - primaza.io
  resources:
  - servicebindings/finalizers
  verbs:
  - update
