apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: pmz:app:${CLUSTER_ENVIRONMENT}:manager
  namespace: system
rules:
- apiGroups:
  - primaza.io
  resources:
  - servicebindings
  - serviceclaims
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - primaza.io
  resources:
  - servicebindings/status
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - get
  - watch
  - update
- apiGroups:
  - primaza.io
  resources:
  - serviceclaims
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - primaza.io
  resources:
  - servicebindings/finalizers
  verbs:
  - update
