name: Create and publish a Docker image

on:  # yamllint disable-line rule:truthy
  push:
    branches: ['main']

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: 'Log in to the Container registry'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Version and Manifests
        run: |
          echo "COMMIT_ID=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV

      - name: 'Build and Push Images with tag COMMIT_ID'
        uses: ./.github/actions/push-ghcr
        with:
          registry: ${{ env.REGISTRY }}
          image_basename: ${{ env.IMAGE_NAME }}
          image_tag: ${{ env.COMMIT_ID }}

      - name: 'Build and Push Images with tag latest'
        uses: ./.github/actions/push-ghcr
        with:
          registry: ${{ env.REGISTRY }}
          image_basename: ${{ env.IMAGE_NAME }}
          image_tag: latest
